name: SimpleMessage
version: 1.20_STABLE
author: KhoaHoangVN
main: vn.khoahoang.simplemsg.SimpleMsg

commands:
  sannounce:
    description: Make an announcement!
    usage: /sannounce <msg>
    aliases: [sa]

permissions:
  simplemsg.protectmode.allowed:
    description: Allow players to break blocks (pass through the Protect Mode)
    default: op
